
---
apiVersion: v1
kind: Service
metadata:
   name: eks-service
   labels:
     name: myapp
spec:
  type: NodePort
  selector:
     name: myapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      


---

apiVersion: app/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
     matchLabels:
       name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
        - name: myapp
          image: nginx
          imagePullPolicy: pull
          ports:
            - containerPort: 8080
